name: Code Review

on:
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.jsx"
      - "**/*.ts"
      - "**/*.tsx"
    branches:
      - main # Change to your default branch

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run code review
        run: node code-review.js # Run the code review script

      - name: Fail the MR if constants are incorrect
        run: |
          if grep -q "🚨 Constants violation detected!" review.txt; then
            echo "🚨 Constants violation detected! Fix before merging.";
            exit 1;
          fi
